# Config file for automatic testing at travis-ci.org

language: python
sudo: false
python:
  - '3.1'
  - '3.2'
  - '3.3'
  - '3.4'
  - '3.5'
  - '3.6'
  - '3.7'
  - '3.8'
  - '3.9'
env:
  DJANGO_VERSION=1.11
  DJANGO_VERSION=2.0
  DJANGO_VERSION=2.1
  DJANGO_VERSION=3.0
  DJANGO_VERSION=3.1
  DJANGO_VERSION=3.1

branches:
  only:
    - master
    - develop
    - /^release\/\d+\.\d+(\.\d+)?(-\S*)?$/

# Command to install dependencies
install:
  - pip install Django==${DJANGO_VERSION}
  - make init

# Command to run tests
script:
  - make yapf
  - make mypy
  - make coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)
